### ISSUE TITLE
LINUX

### ISSUE THREAD

**Issue by DEVIlCHOC** [JaimeFlorian27/reference-importer#3]
Cannot use this in LINUX maya 2020!

**Comment by JaimeFlorian27** [comment]
I will start to develop a multi- platform version as the current version relies on the ffmpeg executable for windows，should be ready in a couple of days

**Comment by MayaUser2024** [comment]
Can you at least update the README? Same problem on a Mac. Installed ffmpeg separately using homebrew, but then it uses FINDSTR which also doesn't exist on Linux or Mac. a simple not saying this is windows only would have helped.

**Comment by JaimeFlorian27** [comment]
Hi! Yeah... I should have been more clear in the video + README a couple of years ago, I pulled this tool together while being an animator without a clear understanding of how to make it work across platforms. The demand for this tool in platforms has grown lately so I'll be happy to take another look. I'll remove the `findstr` dependency in the next release, I'll also distribute a release for each platform that includes the correct ffmpeg binary.
